spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camera_web_seller
    username: root
    password: aogie2003
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: create

server:
  servlet:
    session:
#      timeout: 30
      cookie:
        http-only: true
        secure: false

cors:
  allowed-origins: "*"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600