spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camera_web_seller
    username: sa
    password: 123456789
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: create-drop